// Code generated by MockGen. DO NOT EDIT.
// Source: saver.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLSaverServ is a mock of URLSaverServ interface.
type MockURLSaverServ struct {
	ctrl     *gomock.Controller
	recorder *MockURLSaverServMockRecorder
}

// MockURLSaverServMockRecorder is the mock recorder for MockURLSaverServ.
type MockURLSaverServMockRecorder struct {
	mock *MockURLSaverServ
}

// NewMockURLSaverServ creates a new mock instance.
func NewMockURLSaverServ(ctrl *gomock.Controller) *MockURLSaverServ {
	mock := &MockURLSaverServ{ctrl: ctrl}
	mock.recorder = &MockURLSaverServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLSaverServ) EXPECT() *MockURLSaverServMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockURLSaverServ) Save(ctx context.Context, userID int, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userID, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockURLSaverServMockRecorder) Save(ctx, userID, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockURLSaverServ)(nil).Save), ctx, userID, url)
}

// SaveBatch mocks base method.
func (m *MockURLSaverServ) SaveBatch(ctx context.Context, userID int, urls map[string]string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, userID, urls)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockURLSaverServMockRecorder) SaveBatch(ctx, userID, urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockURLSaverServ)(nil).SaveBatch), ctx, userID, urls)
}
