// Code generated by MockGen. DO NOT EDIT.
// Source: stats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLStatsServ is a mock of URLStatsServ interface.
type MockURLStatsServ struct {
	ctrl     *gomock.Controller
	recorder *MockURLStatsServMockRecorder
}

// MockURLStatsServMockRecorder is the mock recorder for MockURLStatsServ.
type MockURLStatsServMockRecorder struct {
	mock *MockURLStatsServ
}

// NewMockURLStatsServ creates a new mock instance.
func NewMockURLStatsServ(ctrl *gomock.Controller) *MockURLStatsServ {
	mock := &MockURLStatsServ{ctrl: ctrl}
	mock.recorder = &MockURLStatsServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLStatsServ) EXPECT() *MockURLStatsServMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockURLStatsServ) GetStats(ctx context.Context) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStats indicates an expected call of GetStats.
func (mr *MockURLStatsServMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockURLStatsServ)(nil).GetStats), ctx)
}
