version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: shortURL-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./shortURL-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 5
    command: [ "postgres", "-c", "log_statement=all" ]

    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: