BEGIN;

CREATE TABLE IF NOT EXISTS urlshrt (
    id SERIAL PRIMARY KEY,
    short VARCHAR(255) UNIQUE NOT NULL,
    original TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
