// Code generated by MockGen. DO NOT EDIT.
// Source: stats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLStats is a mock of URLStats interface.
type MockURLStats struct {
	ctrl     *gomock.Controller
	recorder *MockURLStatsMockRecorder
}

// MockURLStatsMockRecorder is the mock recorder for MockURLStats.
type MockURLStatsMockRecorder struct {
	mock *MockURLStats
}

// NewMockURLStats creates a new mock instance.
func NewMockURLStats(ctrl *gomock.Controller) *MockURLStats {
	mock := &MockURLStats{ctrl: ctrl}
	mock.recorder = &MockURLStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLStats) EXPECT() *MockURLStatsMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockURLStats) GetStats(ctx context.Context) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStats indicates an expected call of GetStats.
func (mr *MockURLStatsMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockURLStats)(nil).GetStats), ctx)
}
